# BSD 3-Clause License
# Copyright (c) 2022, GM Consult Pty Ltd
# All rights reserved.

# TODO: Edit pubspec.yaml

name: sir_flutter
description: A system for information retrieval (SIR) in Flutter.
version: 0.0.1-1
repository: https://github.com/GM-Consult-Pty-Ltd/sir_flutter
homepage: https://github.com/GM-Consult-Pty-Ltd
issue_tracker: https://github.com/GM-Consult-Pty-Ltd/sir_flutter/issues

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  # -----PubDev Packages (in alphabetic order) -----

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
